### ISSUE TITLE
 ^Versions in package.json

### ISSUE THREAD

**Issue by deniskuznets** [resir014/react-redux-typescript-example#1]
I guess it's better to remove ^ symbol in the package.json because if the newer version with new API of any package will be released, it can crash app while deploying it on a local machine. Removing ^ symbol you can be sure that everything will run ok at anyone local computer.

**Comment by resir014** [comment]
That is why Node projects nowadays provide lockfiles, though. It creates a snapshot of installed packages + its versions when it was first installed, so other people will have the same versions of all packages (including their dependencies) when they install it on their devices as well.

Currently I set up a Yarn lockfile, but I'll also add a npm lockfile if necessary.
