### ISSUE TITLE
Switch from parcel to Create React App (CRA)

### ISSUE THREAD

**Issue by resir014** [resir014/react-redux-typescript-example#14]
Based on @parthopdas' suggestion on #8 I think it'd be better if we switch the initial project setup from parcel to CRA 3.0.

* I initially set up this repo with parcel because it was originally only meant for an example for my [blog post](https://resir014.xyz/posts/2018/07/06/redux-4-plus-typescript/), but since people might be using this template as a starter point, CRA seems like a good choice to reduce the barrier to entry.
* CRA 2.0+ already supports TypeScript out of the box anyway.

**Comment by harshavamsi** [comment]
Agreed. I'd also suggest upgrading the emotion package to v10. There seems to be a lot of difference from the current version. Especially the theming engine and global styles.

**Comment by resir014** [comment]
@harshavamsi That is also being done. #16

**Comment by parthopdas** [comment]
I can pick this up if you wish @resir014, along with the lazy load.
