### ISSUE TITLE
Fetch running on localhost fails

### ISSUE THREAD

**Issue by i-schuetz** [resir014/react-redux-typescript-example#3]
api.opendota.com/api/heroStats:1 Failed to load resource: the server responded with a status of 403 ()
:1234/#/heroes:1 Access to fetch at 'https://api.opendota.com/api/heroStats' from origin 'http://localhost:1234' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
2api.opendota.com/api/teams:1 Failed to load resource: the server responded with a status of 403 ()
:1234/#/teams:1 Access to fetch at 'https://api.opendota.com/api/teams' from origin 'http://localhost:1234' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
2api.opendota.com/api/heroStats:1 Failed to load resource: the server responded with a status of 403 ()
:1234/#/heroes:1 Access to fetch at 'https://api.opendota.com/api/heroStats' from origin 'http://localhost:1234' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by resir014** [comment]
Seems like there's a CORS issue. Looking into it.

**Comment by resir014** [comment]
Should be fixed in f53baa00e1b7a72731d2575542fe53e7802f04c6.
