### ISSUE TITLE
define mapDispatchToProps as object form

### ISSUE THREAD

**Issue by woodsmur** [resir014/react-redux-typescript-example#7]
As it is [recommended by redux doc `always using the “object shorthand” form`](https://react-redux.js.org/using-react-redux/connect-mapdispatch#defining-mapdispatchtoprops-as-an-object), for `mapDispatchToProps` in every page component, maybe one can change:

from 
```
const mapDispatchToProps = (dispatch: Dispatch) => ({
  fetchRequest: () => dispatch(fetchRequest())
})
```

to

```
const mapDispatchToProps = {
  fetchRequest
}
```

for better readability.

**Comment by resir014** [comment]
You're right. I've been using the latter at work and I agree that it's more readable and easier to type.

I'll look into it tonight.

**Comment by AndrewCraswell** [comment]
I just did this a few hours ago while playing with the repo. I submitted PR #9 in case it makes things easier for you.

**Comment by resir014** [comment]
Awesome, thanks!
