### ISSUE TITLE
Code splitting with react-loadable [Question]

### ISSUE THREAD

**Issue by AndrewCraswell** [resir014/react-redux-typescript-example#8]
I've just started a new project at work and have implemented the patterns described in this repository. We're starting with one of our internal React starter kits which has Code Splitting w/ Webpack 4 and TypeScript preconfigured using `react-loadable`. I thought it was cool that the comments in this repo mentioned this approach as recommended. Has anyone done this though? I ran into a lot of errors when configuring my `RouteConfig` and using `ConnectedReduxProps`. I was able to resolve the problem just by removing `ConnectedReduxProps` from the compound type when creating my components. This of course, is not the best solution.

``` typescript
export const routeConfig: RouteConfig[] = [
{
    component: Loadable({
      loader: () => import("./pages/Home/Home"),
      loading: Loading
    }),
    path: "/",
    exact: true
  }
];
```
For reference, the error is being highlighted on the `component` property, and this is what I'm getting:

```
(property) RouteConfig.component?: React.ComponentClass<{} | RouteConfigComponentProps<any>, any> | React.StatelessComponent<{} | RouteConfigComponentProps<any>> | undefined
Type '(ComponentClass<Pick<IAllProps, "dispatch">, any> & LoadableComponent) | (StatelessComponent<Pick<IAllProps, "dispatch">> & LoadableComponent)' is not assignable to type 'ComponentClass<{} | RouteConfigComponentProps<any>, any> | StatelessComponent<{} | RouteConfigComponentProps<any>> | undefined'.
  Type 'ComponentClass<Pick<IAllProps, "dispatch">, any> & LoadableComponent' is not assignable to type 'ComponentClass<{} | RouteConfigComponentProps<any>, any> | StatelessComponent<{} | RouteConfigComponentProps<any>> | undefined'.
    Type 'ComponentClass<Pick<IAllProps, "dispatch">, any> & LoadableComponent' is not assignable to type 'ComponentClass<{} | RouteConfigComponentProps<any>, any>'.
      Types of property 'getDerivedStateFromProps' are incompatible.
        Type 'GetDerivedStateFromProps<Pick<IAllProps, "dispatch">, any> | undefined' is not assignable to type 'GetDerivedStateFromProps<{} | RouteConfigComponentProps<any>, any> | undefined'.
          Type 'GetDerivedStateFromProps<Pick<IAllProps, "dispatch">, any>' is not assignable to type 'GetDerivedStateFromProps<{} | RouteConfigComponentProps<any>, any>'.
            Types of parameters 'nextProps' and 'nextProps' are incompatible.
              Type 'Readonly<{}> | Readonly<RouteConfigComponentProps<any>>' is not assignable to type 'Readonly<Pick<IAllProps, "dispatch">>'.
                Property 'dispatch' is missing in type 'Readonly<{}>' but required in type 'Readonly<Pick<IAllProps, "dispatch">>'.ts(2322)
Home.tsx(27, 3): 'dispatch' is declared here.
Home.tsx(27, 3): 'dispatch' is declared here.
index.d.ts(17, 5): The expected type comes from property 'component' which is declared here on type 'RouteConfig'
```

Is there interest in updating these examples to show code splitting of Redux and Sagas? I was looking at some [Microsoft open source](https://github.com/Microsoft/redux-dynamic-modules) to simplify this solution.

Either way, when we're done with implementing this pattern in our app I'll likely submit a PR with some of our smaller tweaks we felt were an improvement. At the very least it would be helpful to get constructive criticism on the approach.

**Comment by resir014** [comment]
@AndrewCraswell Try something like this:

```tsx
interface RouteConfig {
  component: RouteProps['component']
  path: RouteProps['path']
  exact?: RouteProps['exact']
}

export const routeConfig: RouteConfig[] = [
  {
    component: Loadable({
      loader: () => import('./pages/index'),
      loading: () => <div>Loading...</div>
    }),
    path: '/',
    exact: true
  }
]
```

Also, that pattern documentation is fairly outdated. I'd recommend using [React Suspense](https://reactjs.org/docs/code-splitting.html#reactlazy) if you use a React version which supports it, **and** SSR is not a concern (Suspense doesn't currently support SSR)

**Comment by resir014** [comment]
Disclaimer: I'm not sure the above method works for Redux-connected routes though, so if you know how to fix it, feel free! @AndrewCraswell

**Comment by parthopdas** [comment]
@resir014 @AndrewCraswell react-loadable works great for me with the template.

Given that we now have native support - @resir014 do you think, I could send a 2nd PR to
1. Use react suspense
1. Use redux-dynamic modules

Or would that be an overkill?

In addition - parceljs appears great excepting for complaints online where someone needs to do advanced configuration.

Do you think it makes sense to switch this template over to CRA? It is still 0 config with the option of ejecting.

**Comment by resir014** [comment]
@parthopdas I'm happy to accept PRs for implementing React Suspense! I'll have to think for a while regarding other two though.

**Comment by parthopdas** [comment]
@resir014 will do shortly. i also raised another PR can you please take a look.

**Comment by AndrewCraswell** [comment]
I'm going to close this issue because I think the answer provided is suitable.
